#!/usr/bin/env bash
#create db entry for replication

mysql -uroot -p -e "
CREATE DATABASE IF NOT EXISTS tyrell_corp;
USE tyrell_corp;
CREATE TABLE IF NOT EXISTS nexus6 (
    id int NOT NULL AUTO_INCREMENT,
    name varchar(100) NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO nexus6 (id, name)
VALUES (1, 'Leon');
GRANT SELECT ON tyrell_corp.nexus6 TO 'holberton_user'@'localhost'"
