#!/usr/bin/env bash
# create and write to file. Catch signals
sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
echo "$$" >> /var/run/holbertonscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; echo "I hate the kill command";
exit' SIGQUIT SIGTERM
while :
do
        echo "To infinity and beyond"
        sleep 2
done
