#!/usr/bin/env bash
# create and write to file. Catch signals
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; exit' SIGQUIT SIGTERM
touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
echo "$$" >> /var/run/holbertonscript.pid
while :
do
        echo "To infinity and beyond"
        sleep 2
done
