#!/usr/bin/env bash
#  this script prints "holberton school" + luck
counter=0
while [ $counter -lt 10 ]
do
    ((counter++))
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
	echo "Holberton School"
    fi
done
