#!/usr/bin/env bash
#  this script prints "holberton school" + luck
counter=0
while [ $counter -lt 20 ]
do
    ((counter++))
    case $counter in
	4)
	    echo $counter
	    echo "bad luck from China"
	    continue
	    ;;
	9)
	    echo $counter
	    echo "bad luck from Japan"
	    continue
	    ;;
	17)
	    echo $counter
	    echo "bad luck from Italy"
	    continue
	    ;;

     esac
     echo $counter
done
