#!/usr/bin/env bash
#  this script tells you about HBTN file

file="holbertonschool"
if [ -e "$file" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$file" ]
    then
	echo "holbertonschool file is empty"
    elif [ -s "$file" ]
    then
	echo "holbertonschool file is not empty"
    fi
    if [ -f "$file" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
	echo "holbertonschool file does not exist"
fi
