#!/usr/bin/env bash
# install nginx server
apt-get install nginx -y
cd /etc/nginx/
mkdir html
cd html
touch index.html
path="/etc/nginx/sites-available"
echo "server {
    listen 80 default_server;
    location / {
        root /etc/nginx/html;
        index index.html;
    }
}" > "$path/default"
echo "Holberton School for the win!" > /etc/nginx/html/index.html
service nginx restart
