#!/usr/bin/env bash
# run nginx as master process
sudo pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
